### ISSUE TITLE
Installing matplotlib-base with conda lists matplotlib as installed from pip

### ISSUE THREAD

**Issue by mdeff** [conda-forge/matplotlib-feedstock#182]
Installing `matplotlib-base` with conda lists `matplotlib` as installed from pip.

Steps to reproduce:
1. Install with `conda create -n test matplotlib-base`. My `.condarc` will only allow packages to be fetched from `conda-forge`, not `defaults`.
2. The environment exported with `conda env export -n test` contains the below.
   ```
   name: test
   channels:
     - conda-forge
   dependencies:
     - some-other-packages
     - matplotlib-base=3.0.0=py37hc039c98_2
     - some-other-packages
     - pip:
       - matplotlib==3.0.0
   ```

I understand #178 is a new development and this issue is not a big deal (compared to the advantages of the split). I just wanted to let you know. Ping @marcelm, and thanks for your work. :)
